version: "3.2"
services:
  redis:
      image: redis
      hostname: redis
      container_name: s3xy_redis
      ports:
        - "6379:6379"
  ceph:
    build:
      context: .
      dockerfile: Dockerfile-ceph
    environment:
      - RGW_USER=s3xy
      - RGW_USER_USER_KEY=s3xy
      - RGW_USER_SECRET_KEY=s3xy
      - CEPH_DAEMON=demo
      - CEPH_DEMO_UID=s3xy
      - CEPH_VERSION=luminous
      - DEBUG=verbose
      - DEMO_DAEMONS=mon,mgr,osd,rgw
      - EXPOSED_IP=0.0.0.0
      - HOSTNAME=
      - NETWORK_AUTO_DETECT=4
      - RGW_CIVETWEB_PORT=80
      - SHLVL=2
      - SREE_PORT=5000
      - container=oci
    volumes:
      - /etc/ceph:/etc/ceph
